openapi: 3.0.3
info:
  title: Project Service API
  version: "1.0.0"
servers:
  - url: http://localhost:8081
    description: Local Project Service
security:
  - bearerAuth: []
paths:
  /api/projects:
    post:
      summary: Create a project
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjectRequest'
      responses:
        '201':
          description: Project created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'
    get:
      summary: List projects
      parameters:
        - in: query
          name: status
          schema:
            $ref: '#/components/schemas/ProjectStatus'
        - in: query
          name: customerId
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Projects collection
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectResponse'
  /api/projects/{projectId}:
    get:
      summary: Get project by id
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Project details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'
  /api/projects/{projectId}/status:
    patch:
      summary: Update project status
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProjectStatusRequest'
      responses:
        '200':
          description: Updated project
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'
  /api/projects/{projectId}/quotes:
    post:
      summary: Create project quote
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateQuoteRequest'
      responses:
        '201':
          description: Quote created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteDetailResponse'
  /api/quotes/{quoteId}/approve:
    post:
      summary: Approve a quote
      parameters:
        - in: path
          name: quoteId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Approved quote
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteDetailResponse'
  /api/quotes/{quoteId}/reject:
    post:
      summary: Reject a quote
      parameters:
        - in: path
          name: quoteId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Rejected quote
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteDetailResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CreateProjectRequest:
      type: object
      required:
        - customerId
        - title
      properties:
        customerId:
          type: string
          format: uuid
        title:
          type: string
          maxLength: 120
    UpdateProjectStatusRequest:
      type: object
      required:
        - newStatus
      properties:
        newStatus:
          $ref: '#/components/schemas/ProjectStatus'
    CreateQuoteRequest:
      type: object
      required:
        - total
      properties:
        total:
          type: number
          format: decimal
          minimum: 0.01
    ProjectResponse:
      type: object
      required:
        - projectId
        - customerId
        - title
        - status
        - createdAt
        - updatedAt
        - tasks
        - quotes
        - statusHistory
      properties:
        projectId:
          type: string
          format: uuid
        customerId:
          type: string
          format: uuid
        title:
          type: string
        status:
          $ref: '#/components/schemas/ProjectStatus'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/TaskResponse'
        quotes:
          type: array
          items:
            $ref: '#/components/schemas/QuoteDetailResponse'
        statusHistory:
          type: array
          items:
            $ref: '#/components/schemas/StatusHistoryResponse'
    TaskResponse:
      type: object
      required:
        - taskId
        - title
        - estimateHours
        - status
      properties:
        taskId:
          type: string
          format: uuid
        title:
          type: string
        estimateHours:
          type: number
        assigneeId:
          type: string
          format: uuid
          nullable: true
        status:
          type: string
    StatusHistoryResponse:
      type: object
      required:
        - id
        - fromStatus
        - toStatus
        - changedBy
        - changedAt
      properties:
        id:
          type: integer
          format: int64
        fromStatus:
          $ref: '#/components/schemas/ProjectStatus'
        toStatus:
          $ref: '#/components/schemas/ProjectStatus'
        changedBy:
          type: string
          format: uuid
        changedAt:
          type: string
          format: date-time
    QuoteDetailResponse:
      type: object
      required:
        - quoteId
        - projectId
        - total
        - status
        - issuedAt
      properties:
        quoteId:
          type: string
          format: uuid
        projectId:
          type: string
          format: uuid
        total:
          type: number
          format: decimal
        status:
          $ref: '#/components/schemas/QuoteStatus'
        issuedAt:
          type: string
          format: date-time
        approvedAt:
          type: string
          format: date-time
          nullable: true
    ProjectStatus:
      type: string
      enum:
        - Requested
        - Quoted
        - Approved
        - InProgress
        - Completed
        - Cancelled
    QuoteStatus:
      type: string
      enum:
        - Draft
        - Approved
        - Rejected
