ALTER TABLE invoices
    ALTER COLUMN currency TYPE VARCHAR(3),
    ALTER COLUMN currency SET DEFAULT 'LKR';

ALTER TABLE payments
    ALTER COLUMN currency TYPE VARCHAR(3),
    ALTER COLUMN currency SET DEFAULT 'LKR';
